export enum MeldMode {
    CONCEALED_PAIR = 'CONCEALED_PAIR',
    EXPOSED_PAIR = 'EXPOSED_PAIR',
    CONCEALED_CHOW = 'CONCEALED_CHOW',
    EXPOSED_CHOW = 'EXPOSED_CHOW',
    CONCEALED_PONG = 'CONCEALED_PONG',
    EXPOSED_PONG = 'EXPOSED_PONG',
    CONCEALED_KONG = 'CONCEALED_KONG',
    EXPOSED_KONG = 'EXPOSED_KONG'
}